# ~/.codex/config.toml — BALANCED

model = "gpt-5"

# Fewer prompts: the model asks only when it believes extra privileges are needed.
approval_policy = "on-request"

# Keep OS sandboxing; allow writes in the workspace and temp dirs.
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
# Enable outbound network for installs, git fetch, API calls—still inside the sandbox.
network_access = true
# Example: add extra writable roots if you need local tool caches (optional)
# writable_roots = ["~/.cache/pip", "~/.npm"]

[shell_environment_policy]
# Start from the full environment but tightly whitelist what survives.
inherit = "all"
# Keep the default filter that drops names containing KEY/SECRET/TOKEN.
ignore_default_excludes = false
# Only pass through these common, low-risk vars (add more if you need them).
include_only = [
  "PATH", "HOME", "USER", "SHELL",
  "LANG", "LC_*",
  "TERM",
  "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY",
  # Uncomment specific safe tool vars you rely on:
  # "JAVA_HOME", "GOPATH", "RUSTUP_HOME", "CARGO_HOME", "PYENV_*", "NVM_DIR"
]
# Optional explicit overrides:
# set = { CI = "1" }

# Optional: keep local history (default) or harden privacy:
# [history]
# persistence = "none"
